(eval-when-compile (require 'cl))

(require 'iota4e-main)     ;; main screen
(require 'iota4e-meta)     ;; autogenerated file with metadata (version etc.)
(require 'iota4e-proc)     ;; communication with backend
(require 'iota4e-utils)    ;; utility functions
(require 'iota4e-headers)


(setq iota4e-header-func  'iota4e~headers-header-handler)
(setq iota4e-found-func   'iota4e~headers-found-handler)
(setq iota4e-view-func    'iota4e~headers-view-handler)

;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;###autoload
(defun iota4e()
  "Start iota4e."
  (interactive)
  ;; start iota4e, then show the main view
  (iota4e~start 'iota4e~main-view))

(defun iota4e-test()
  (iota4e~proc-send-command "find %s" "test"))

(defun iota4e-quit()
  "Quit the iota4e session."
  (interactive)
  (iota4e~stop))
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(provide 'iota4e)
;;; iota4e.el ends here
